name: Wiki Updates to Slack

on:
  gollum: # GitHub Wiki (Gollum) 이벤트가 발생할 때 이 워크플로우를 트리거합니다.
    types: [created, edited, deleted] # Wiki 페이지가 생성, 편집, 삭제될 때 실행됩니다.

jobs:
  notify-slack:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 # 저장소 코드를 체크아웃합니다.

    - name: Send Wiki update to Slack
      #  이 부분을 adriennedominguez/gollum-page-watcher@v1 로 수정해야 합니다.
      uses: adriennedominguez/gollum-page-watcher@v1
      with:
        slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }} # Slack Webhook URL을 전달합니다.
        # 참고: gollum-page-watcher 액션은 message_template 대신 다양한 커스텀 메시지 옵션을 제공합니다.
        # 자세한 내용은 액션 문서 (https://github.com/adriennedominguez/gollum-page-watcher)를 참조하세요.
        # 예시:
        custom-message: |
          {{ page.action_verb }} happened on {{ page.full_name }} by {{ page.actor.display_login }} at {{ page.page_url }}